version: "3"
services:
  db:
    image: mysql:8.0.2
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db-data:/var/lib/mysql
  web:
    image: golang:1.8.3
    depends_on:
      - db
volumes:
  db-data:
